name: micro_flutter
description: "组件化解决方案"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  # 添加module 组件引用
  core:
    path: modules/core
  network:
    path: modules/network
  router_path:
    path: modules/router_path
  login:
    path: modules/login
  home:
    path: modules/home
  profile:
    path: modules/profile
  chat:
    path: modules/chat
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  melos: ^6.1.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true           # 启用 Android 图标生成
  ios: true               # 启用 iOS 图标生成
  image_path: "assets/imgs/app_icon.png"  # 指定你的应用图标路径
  # 运行命令： flutter pub run flutter_launcher_icons:main