name: assets
description: "资源管理模块"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.12

flutter:
  assets:
    - assets/images/
    - assets/images/commons/
    - assets/images/login/

flutter_gen:
  output: lib/gen/  # 设置生成的文件位置
  assets:
    enabled: true  # 启用图片资源管理
  fonts:
    enabled: true  # 启用字体资源管理
